name: magnifying_glass
description: Flutter real-time magnifying glass lens widget with Barrel/Pincushion distortion.
version: 1.0.2
homepage: https://github.com/alnitak/magnifying_glass
issue_tracker: https://github.com/alnitak/magnifying_glass/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_web_plugins:
#    sdk: flutter

  # https://pub.dev/packages/ffi
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bavagnoli.magnifying_glass
        pluginClass: MagnifyingGlassPlugin
      ios:
        pluginClass: MagnifyingGlassPlugin
      linux:
        pluginClass: MagnifyingGlassPlugin
      macos:
        pluginClass: MagnifyingGlassPlugin
      windows:
        pluginClass: MagnifyingGlassPlugin

#      web:
#        pluginClass: MagnifyingGlassWeb
#        fileName: magnifying_glass_web.dart
