name: magnifying_glass
description: Magnifying Glass
version: 1.0.0
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # https://pub.dev/packages/ffi
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bavagnoli.magnifying_glass
        pluginClass: MagnifyingGlassPlugin
      ios:
        pluginClass: MagnifyingGlassPlugin
      linux:
        pluginClass: MagnifyingGlassPlugin
      web:
        pluginClass: MagnifyingGlassWeb
        fileName: magnifying_glass_web.dart
